language: go

go:
  - 1.6
  - 1.5
  - 1.4
  - 1.3
  - release

before_install:
  - go get github.com/nbio/st
  - go get -u gopkg.in/h2non/gentleman.v0
  - go get -u gopkg.in/h2non/gock.v0
  - go get -u gopkg.in/h2non/gentleman-mock.v0
  - go get -u gopkg.in/eapache/go-resiliency.v1/retrier
  - go get -u gopkg.in/h2non/gentleman-retry.v0
  - go get -u github.com/hashicorp/consul/api
  - go get -u -v github.com/axw/gocov/gocov
  - go get -u -v github.com/mattn/goveralls
  - go get -u -v github.com/golang/lint/golint

script:
  - diff -u <(echo -n) <(gofmt -s -d ./)
  - diff -u <(echo -n) <(go vet ./...)
  - diff -u <(echo -n) <(golint ./...)
  - go test -v -race -covermode=atomic -coverprofile=coverage.out

after_success:
  - goveralls -coverprofile=coverage.out -service=travis-ci -repotoken $COVERALLS_TOKEN
